package sn.free.selfcare.domain.enumeration;

/**
 * The ParameterOption enumeration.
 */
public enum ParameterOption {
	FREE_RAISON_SOCIALE, FREE_EMAIL, FREE_CALL_CENTER, FREE_COMPTE_BANQUE, PERIODE_ENVOI_RESSOURCE_MENSUEL, PERIODE_ENVOI_RESSOURCE_HEBDOMADAIRE, PERIODE_ENVOI_RESSOURCE_QUOTIDIEN;

}
